name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: building & testing
        run: docker build . -f Dockerfile -t fse_test
      - name: check prereq
        run: docker run --rm -v ./dataset/:/mnt/data fse_test:latest make -f /mnt/code/Makefile_docker prereqs
      - name: building_check
        run: docker run --rm -v ./dataset/:/mnt/data fse_test:latest make -f /mnt/code/Makefile_docker build
      - name: tests
        run: docker run --rm -v ./dataset/:/mnt/data fse_test:latest make -f /mnt/code/Makefile_docker test
